### ISSUE TITLE
Accessibility assistant shows empty error messages

### ISSUE THREAD

**Issue by Jantine** [quailjs/quail-ckeditor#3]
![screen shot 2014-07-03 at 14 37 24](https://cloud.githubusercontent.com/assets/8058137/3469462/e26045c2-02ae-11e4-9e25-76b78cc9b297.png)
![screen shot 2014-07-03 at 14 37 14](https://cloud.githubusercontent.com/assets/8058137/3469463/e5fe9ed6-02ae-11e4-8e5d-193f7a20623b.png)

Browser: Firefox 30.0
CMS: Hippo
Editor: CKEditor
Situation: Plug-in highlights error, but does not show error message in pop-up. See screen shots where bold piece of content is marked, but no message appears in the pop-up.
Expected situation: When an error is marked and clicked, the pop-up contains an error message

**Comment by jessebeach** [comment]
I think we're using the standard CKEditor dialogs. I'm not sure how we change this.

**Comment by jessebeach** [comment]
Derp! I misunderstood. Kevin should have fixed this and the change is in the 0.1.0 tag.
