### ISSUE TITLE
Accessibility plug-in does not pick up inconsistent header use

### ISSUE THREAD

**Issue by Jantine** [quailjs/quail-ckeditor#4]
![screen shot 2014-07-03 at 14 39 16](https://cloud.githubusercontent.com/assets/8058137/3469511/80fbbe6e-02af-11e4-9ddf-216055d4bf90.png)

Browser: Firefox 30.0
CMS: Hippo
Editor: CKEditor
Situation: I've put in a header 2 followed by a paragraph then a header 4 followed by a paragraph. The plug-in should mark this, but when activated, does not give a dotted line.
Expected situation: The plug-in picks up this wrong header use

**Comment by jessebeach** [comment]
I've added more tests to the example implementation. This is a configuration issue. I can help get your configuration updated.
